apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-connector
  namespace: ai-platform
  labels:
    app: data-connector
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-connector
  template:
    metadata:
      labels:
        app: data-connector
        component: backend
    spec:
      containers:
      - name: data-connector
        image: data-connector:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http
        - containerPort: 1883
          name: mqtt
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-platform-secrets
              key: database-url
        - name: AI_CORE_URL
          value: "http://ai-core:8000"
        - name: MQTT_BROKER
          value: "localhost"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: data-connector
  namespace: ai-platform
  labels:
    app: data-connector
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  - port: 1883
    targetPort: 1883
    protocol: TCP
    name: mqtt
  selector:
    app: data-connector

